### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by mpadge** [moveability/moveability#2]
Thanks for doing this! Please just do these 2 minor things:

1. Download the data from [this release page](https://github.com/ATFutures/moveability/releases/tag/v0) for MS and Dresden, and rbind them into one data.frame
2. Rename the resultant file in `docs/` to `index.html`, because that's what `gh-pages` expects.

This code can be used:
``` r
m1 <- readRDS ("moveability-ms.Rds")
m1$m <- 20 * m1$m / max (m1$m) # Each set has to be re-scaled independently
m2 <- readRDS ("moveability-dres.Rds")
m2$m <- 20 * m2$m / max (m2$m)
m <- rbind (m1, m2)
library (mapdeck)
set_token (Sys.getenv ("MAPBOX_TOKEN"))
loc <- c (mean (m$x), mean (m$y))
mapdeck (style = 'mapbox://styles/mapbox/dark-v9',
         zoom = 7, # -------------- Note: zoom = 7 -------------------
         location = loc) %>%
    add_pointcloud (data = m,
              layer_id = "walkability",
              lon = "x",
              lat = "y",
              radius = 10,
              fill_colour = "m",
              palette = "inferno")
```

**Comment by silberzwiebel** [comment]
Ok, it works at my forked repo, even with html-files different than `index.html`:
https://silberzwiebel.github.io/moveability/docs/
https://silberzwiebel.github.io/moveability/docs/muenster.html
https://silberzwiebel.github.io/moveability/docs/dresden.html

It doesn't work at https://atfutures.github.io/moveability/docs/ or https://atfutures.github.io/moveability/ but I suppose this is due to the fact that [this repo](https://github.com/ATFutures/atfutures.github.io) is already configured for the ATFutures github-pages?

**Comment by mpadge** [comment]
Okay, then I'll copy it over to the main repo. Great sleuthing, thanks

**Comment by mpadge** [comment]
[https://atfutures.github.io/maps/moveability](https://atfutures.github.io/maps/moveability). Not the recommended approach, but I just static-copied the files over to that directory of the `github.io` repo (in [this commit](https://github.com/ATFutures/atfutures.github.io/commit/f806fb3cdd084c301e9da6cb8d52786335065a21)), and presto!
